spring:
  application:
    name: spring-food
  freemarker:
    settings:
      locale: pt_BR
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: development
  resources:
    add-mappings: false
foodapi:
  group:
    admin: ADMIN
    master: MASTER